from .cancel_appt import cancel_appt_name
from .cancel_appt import cancel_appt1
from .cetak_appt import get_data_appt
from .cetak_appt import input_name
from .cetak_appt import get_data
from .login_appt import login
from .new_appt import owner_name
from .new_appt import patient_name
from .new_appt import breed
from .new_appt import sex
from .new_appt import age
from .new_appt import med_treat
from .new_appt import date
from .print_bill import get_medtreat_data
from .print_bill import get_price